### ISSUE TITLE
catch and display friendly error on missing S3 configuration

### ISSUE THREAD

**Issue by eads** [thecarebot/carebot#345]

**Comment by eads** [comment]
Right now you get something like:

```
$ python carebot.py
/Users/davideads/VirtualEnvs/carebot/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "carebot.py", line 10, in <module>
    from util.slack import SlackTools
  File "/Users/davideads/Projects/carebot/util/slack.py", line 8, in <module>
    from util.chart import ChartTools
  File "/Users/davideads/Projects/carebot/util/chart.py", line 16, in <module>
    s3 = Uploader()
  File "/Users/davideads/Projects/carebot/util/s3.py", line 14, in __init__
    self.bucket = self.s3.Bucket(app_config.S3_BUCKET)
  File "/Users/davideads/VirtualEnvs/carebot/lib/python2.7/site-packages/boto3/resources/factory.py", line 452, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/Users/davideads/VirtualEnvs/carebot/lib/python2.7/site-packages/boto3/resources/base.py", line 119, in __init__
    'Required parameter {0} not set'.format(identifier))
ValueError: Required parameter name not set
```

**Comment by mdeggies** [comment]
+1
